name: First workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest 
        steps:
            - name : checkout
              uses : actions/checkout@v4
            - name : welcome message
              run: echo " my fist github action job"

            - name : list files
              run: ls

            

          